# A basic redirect rule
[[redirects]]
  from = "/"
  to = "https://anit.cc"

baseurl = "/"
title = "Anit Shrestha Manandhar | Software Engineer"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Hi I'm Anit."
    info = "I help startups in web/mobile application development."
    description = "Personal website of Anit Shrestha Manandhar | Software Engineer | Software Developer | Programmers"
    keywords = "personal website, software engineer, software developer, programmer"
    avatarurl = ""

    favicon_32 = "/images/favicon.ico"
    favicon_16 = "/images/favicon.ico"

    footercontent = "Websites for everyone."

    hidecredits = false
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/anit"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook fa-2x"
    weight = 2
    url = "https://www.facebook.com/anit01"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/allegorythm"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 4
    url = "https://stackoverflow.com/story/anit"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 5
    url = "https://github.com/anit01"
[[params.social]]
    name = "Youtube"
    icon = "fab fa-youtube fa-2x"
    weight = 6
    url = "https://www.youtube.com/c/AnitShrestha"
[[params.social]]
    name = "Goodreads"
    icon = "fab fa-readme fa-2x"
    weight = 7
    url = "https://www.goodreads.com/anit01"
